# Generated by Django 6.0.6 on 2026-07-07 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('reporters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record_no', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('is_breast_feeding', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.gender')),
                ('health_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporters.healthfacility')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.province')),
            ],
            options={
                'db_table': 'patients',
            },
        ),
    ]
