# Generated by Django 6.0.6 on 2026-07-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='health_facility',
        ),
    ]
