# Generated by Django 6.0.6 on 2026-07-07 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugs', '0001_initial'),
        ('patients', '0001_initial'),
        ('reporters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_start_date', models.DateField(blank=True, null=True)),
                ('reaction_end_date', models.DateField(blank=True, null=True)),
                ('reaction_description', models.TextField()),
                ('medical_history', models.TextField(blank=True)),
                ('allergy_history', models.TextField(blank=True)),
                ('time_interval_drug_reaction', models.CharField(blank=True, max_length=100)),
                ('drug_stopped', models.BooleanField(default=False)),
                ('reaction_reduce_after_stopping', models.BooleanField(default=False)),
                ('dose_reduced', models.BooleanField(default=False)),
                ('reaction_reduce_after_dose_reduction', models.BooleanField(default=False)),
                ('drug_restarted', models.BooleanField(default=False)),
                ('reaction_returned_after_restart', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'adverse_reactions',
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'outcomes',
            },
        ),
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'report_statuses',
            },
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'severities',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.IntegerField()),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='LaboratoryInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_type', models.CharField(max_length=200)),
                ('investigation_result', models.TextField(blank=True)),
                ('investigation_date', models.DateField(blank=True, null=True)),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.adversereaction')),
            ],
            options={
                'db_table': 'laboratory_investigations',
            },
        ),
        migrations.AddField(
            model_name='adversereaction',
            name='outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.outcome'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=30, unique=True)),
                ('report_date', models.DateField()),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporters.reporter')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.reportstatus')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(max_length=30)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporters.reporter')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            options={
                'db_table': 'attachments',
            },
        ),
        migrations.AddField(
            model_name='adversereaction',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
        migrations.CreateModel(
            name='ReportDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('indication', models.TextField(blank=True)),
                ('treatment_start_date', models.DateField(blank=True, null=True)),
                ('treatment_stop_date', models.DateField(blank=True, null=True)),
                ('treatment_duration', models.CharField(blank=True, max_length=100)),
                ('is_treatment_ongoing', models.BooleanField(default=False)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drugs.drug')),
                ('drug_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drugs.drugtype')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_drugs', to='reports.report')),
            ],
            options={
                'db_table': 'report_drugs',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=30)),
                ('review_comment', models.TextField(blank=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.AddField(
            model_name='adversereaction',
            name='severity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.severity'),
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('new_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_status', to='reports.reportstatus')),
                ('old_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='old_status', to='reports.reportstatus')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            options={
                'db_table': 'status_history',
            },
        ),
    ]
