# Generated by Django 6.0.6 on 2026-07-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='registration_number',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
    ]
