# Generated by Django 6.0.6 on 2026-07-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='registration_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
