# Generated by Django 6.0.6 on 2026-07-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auditlog_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reportstatus',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='severity',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reportstatus',
            name='status_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
