# Generated by Django 6.0.6 on 2026-07-07 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_type_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'reporter_types',
            },
        ),
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_facilities', to='common.province')),
            ],
            options={
                'db_table': 'health_facilities',
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('stamp_image', models.ImageField(blank=True, null=True, upload_to='stamps/')),
                ('registration_date', models.DateField()),
                ('health_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporters.healthfacility')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.province')),
                ('reporter_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporters.reportertype')),
            ],
            options={
                'db_table': 'reporters',
            },
        ),
    ]
