# Generated by Django 6.0.6 on 2026-07-07 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter',
            name='province',
        ),
    ]
