# Generated by Django 6.0.6 on 2026-07-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0002_remove_reporter_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportertype',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
