# Generated by Django 6.0.6 on 2026-07-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0003_reportertype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportertype',
            name='code',
            field=models.CharField(default=1, max_length=20, unique=True),
        ),
    ]
