# Generated by Django 6.0.6 on 2026-07-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0004_alter_reportertype_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportertype',
            old_name='reporter_type_name',
            new_name='reporter_type',
        ),
        migrations.AlterField(
            model_name='reportertype',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
