# Generated by Django 6.0.6 on 2026-07-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0005_rename_reporter_type_name_reportertype_reporter_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter',
            name='organization_name',
        ),
    ]
