# Generated by Django 6.0.6 on 2026-07-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0006_remove_reporter_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportertype',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
