# Generated by Django 6.0.6 on 2026-07-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporters', '0007_alter_reportertype_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter',
            name='stamp_image',
        ),
    ]
